### PR TITLE
fix(@nanoexpress/middleware-schemator): Fix import config file in Windows

### PR DESCRIPTION
**Pull request by Team-OF**
### Is you/your team sponsoring this project

- [ ] Yes
- [x] No

### What you changed

- [x] Code changes
- [ ] Tests changed
- [ ] Typo fixes

### Note

- **Your every change to feature/code should be documented**
- **📝 Documentation** fixes should be filled [here](https://github.com/nanoexpress/docs/pulls)
- **nanoexpress** fixes should be filled [here](https://github.com/nanoexpress/pro/pulls)

### CODE REVIEW

**Comment by dalisoft** [comment]
Please fix commit style

**Comment by dalisoft** [comment]
No, it’s wrong. Please update commit message. Commit message should be like this https://github.com/nanoexpress/middlewares/commit/99813a0754fd458630e4ee71a1e0df8974266c15

**Comment by Team-OF** [comment]
is that cool?

**Comment by dalisoft** [comment]
Commit message also should be same as title

**Comment by dalisoft** [comment]
@Team-OF Re-create PR with commit message `fix(@nanoexpress/middleware-schemator): Fix import config file in Windows`, there are few steps for example

```bash
# you edit files
git add -A packages/schemator
git commit -m "fix(@nanoexpress/middleware-schemator): Fix import config file in Windows"
git push
```

**Comment by torbjorn-kvist** [comment]
This "fix" breaks on debian (linux), as this removes the first '/' in the path using the substring(1)
`Error: ENOENT: no such file or directory, open 'home/user/code/backend/swagger.yml'`

The path on debian should be `/home/user/code/backend/swagger.yml`
If the fix is needed for windows, what kind of error did @SecretsNetwork get with the previous solution?

**Pull request closed without merging**
